language: php

dist: trusty

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

before_script:
  - composer install --prefer-source

script:
  - composer test

cache:
  directories:
    - $HOME/.composer/cache
