language: php

dist: trusty

php:
  - 7.2
  - hhvm

before_script:
  - composer install --prefer-source

script:
  - composer test

after_success:
  - if [[ "`phpenv version-name`" != "7.1" ]]; then exit 0; fi
  - phpunit --coverage-clover coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

cache:
  directories:
    - $HOME/.composer/cache
